<?php
$title = 'Domains';
$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<table border="0" width="100%">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th><a href="<?php echo $this->url('domain', array('action' => 'add')); ?>" title="Add a domain.">Add +</a></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($domains as $domain): ?>
        <tr>
            <td><?php echo (int) $domain->getId(); ?></td>
            <td>
                <a href="<?php echo $this->url('domain', array('action' => 'view', 'id' => (int) $domain->getId())); ?>">
                <?php echo $this->escapeHtml($domain->getName()); ?>
                </a>
            </td>
            <td>
                <a href="<?php echo $this->url('domain', array('action' => 'edit', 'id' => (int) $domain->getId())); ?>"
                   class="label primary small round"
                   title="Edit domain <?php echo (int) $domain->getId(); ?>">Edit</a>
                &nbsp;
                <a href="<?php echo $this->url('domain', array('action' => 'delete', 'id' => (int) $domain->getId())); ?>"
                   class="label alert small round"
                   title="Edit domain <?php echo (int) $domain->getId(); ?>">Delete</a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php
    echo $this
        ->paginationControl($this
            ->paginator, 'sliding' ,array('partial/paginator.phtml', 'Flashcard'), array('route' => 'domainIndex'));
?>
