<?php
$title = 'Delete user';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
  '<?php echo $this->escapeHtml($user->getUsername()); ?>'?
</p>
<?php
$url = $this->url('useradmin', array('action' => 'delete', 'id'=> $id)); ?>
<form action="<?php echo $url; ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?php echo (int)$user->getId(); ?>" />
  <input onclick="return confirm('Are you sure?  This cannot be undone!')"
         type="submit" name="del" value="Yes" class="button alert" />
  <input type="submit" name="del" value="No" class="button success" />
</div>
</form>
