<?php
$title = $category->getName() . ' Questions';
$this->headTitle($title);
?>

<?php
    function trimString($string) {
        return (strlen($string) > 90) ? substr($string, 0, 90) . '...' : $string;
    }
?>

<h2><?php echo $this->escapeHtml($title); ?></h2>

<table border="0" width="100%">
    <thead>
        <tr>
            <th>Wt</th>
            <th>Id</th>
            <th>Question</th>
            <th>Category</th>
            <th>Doamin</th>
            <th><a href="<?php echo $this
                ->url('question', array('action' => 'add', 'id' => (int) $category->getId())); ?>"
                title="Add a question.">Add +</a></th>
        </tr>
    </thead>
    <tbody id="sortable">
        <?php foreach($questions as $question): ?>
        <tr id="<?php echo $question->getId(); ?>" entity="Question" offset="<?php echo $offset; ?>">
            <td>
                <span id="weight-button-<?php echo (int) $question->getID(); ?>"
                        class="weight-button handle">
                    <?php echo (int) $question->getWeight(); ?>
                </span>
                <?php
                $question->weightForm->setAttribute('action', $this->url('weight-rest'));
                $question->weightForm->prepare();
                echo $this->form()->openTag($question->weightForm) . PHP_EOL;
                echo $this->formHidden($question->weightForm->get('csrf')) . PHP_EOL;
                echo $this->form()->closeTag($question->weightForm) . PHP_EOL;
                ;?>
            </td>
            <td><?php echo (int) $question->getId(); ?></td>
            <td>
                <a href="<?php echo $this->url('question', array('action' => 'view', 'id' => (int) $question->getId())); ?>">
                <?php echo trimString($this->escapeHtml($question->getQuestion())); ?>
                </a>
            </td>
            <td><?php echo $this->escapeHtml($question->getCategory()->getName()); ?></td>
            <td>
                <a href="<?php echo $this->url('domain', array('action' => 'view', 'id' => (int) $question->getCategory()->getDomain()->getId())); ?>">
                <?php echo trimString($this->escapeHtml($question->getCategory()->getDomain()->getName())); ?>
                </a>
            </td>
            <td>
                <a href="<?php echo $this->url('question', array('action' => 'edit', 'id' => (int) $question->getId())); ?>"
                   class="label primary small round"
                   title="Edit question <?php echo (int) $question->getId(); ?>">Edit</a>
                &nbsp;
                <a href="<?php echo $this->url('question', array('action' => 'delete', 'id' => (int) $question->getId())); ?>"
                   class="label alert small round"
                   title="Edit question <?php echo (int) $question->getId(); ?>">Delete</a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php
    echo $this
        ->paginationControl($this
            ->paginator, 'sliding',
            array('partial/paginator.phtml', 'Flashcard'),
            array('route' => 'category', 'action' => 'view', 'id' => $category_id));
?>
<br/><br/>
<p><a href="<?php echo $this->url('question', array('action' => 'add', 'id' => (int) $category->getId())); ?>"
   title="Add a question."
   class="button">
    Add +
</a></p>
