<?php
    $title = 'Add Question';
    $this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>

<?php
$form->setAttribute('action', $this->url('question', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formHidden($form->get('csrf')) . PHP_EOL;
echo $this->formRow($form->get('question')) . PHP_EOL;
echo $this->formRow($form->get('answer')) . PHP_EOL;
echo $this->formRow($form->get('note')) . PHP_EOL;
echo $this->formRow($form->get('category_options')) . PHP_EOL;
echo $this->formInput($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;
?>
