<?php $title = $question->getCategory()->getName(); ?>
<?php $this->headTitle($title); ?>

<h2><?php echo $this->escapeHtml($title); ?></h2>

<input type="hidden" class="question"
           name="question-<?php echo (int) $question->getId(); ?>"
           value="<?php echo $this->escapeHtml($question->getQuestion()); ?>"
           answer="<?php echo $this->escapeHtml($question->getAnswer()); ?>"
           note="<?php echo $this->escapeHtml($question->getNote()); ?>"
           />

<p class="panel" id="qna-panel"></p>
<p><button id="show-answer-button" class="button success">Show answer</button></p>
<p><button id="show-question-button" class="button secondary">Show question</button></p>
<p>
    <a href="<?php echo $this
        ->url('category',array('action' => 'view', 'id' => $question->getCategory()->getId())); ?>"
        id="back-to-category-button" class="button">
        Back to category
    </a>
</p>

