<!-- Included JS Files (Uncompressed) -->
<!--
<script src="javascripts/jquery.js"></script>
<script src="javascripts/jquery.foundation.mediaQueryToggle.js"></script>
<script src="javascripts/jquery.foundation.forms.js"></script>
<script src="javascripts/jquery.event.move.js"></script>
<script src="javascripts/jquery.event.swipe.js"></script>
<script src="javascripts/jquery.foundation.reveal.js"></script>
<script src="javascripts/jquery.foundation.orbit.js"></script>
<script src="javascripts/jquery.foundation.navigation.js"></script>
<script src="javascripts/jquery.foundation.buttons.js"></script>
<script src="javascripts/jquery.foundation.tabs.js"></script>
<script src="javascripts/jquery.foundation.tooltips.js"></script>
<script src="javascripts/jquery.foundation.accordion.js"></script>
<script src="javascripts/jquery.placeholder.js"></script>
<script src="javascripts/jquery.foundation.alerts.js"></script>
<script src="javascripts/jquery.foundation.topbar.js"></script>
<script src="javascripts/jquery.foundation.joyride.js"></script>
<script src="javascripts/jquery.foundation.clearing.js"></script>
<script src="javascripts/jquery.foundation.magellan.js"></script>
-->

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<?php echo $this->headScript()
    ->prependFile($this->basePath() . '/javascripts/foundation3/app.js')
    ->prependFile($this->basePath() . '/javascripts/foundation3/jquery.foundation.forms.js')
    ->prependFile($this->basePath() . '/javascripts/foundation3/jquery.foundation.topbar.js')
    ->prependFile($this->basePath() . '/javascripts/markitup/sets/html/set.js')
    ->prependFile($this->basePath() . '/javascripts/markitup/jquery.markitup.js')
    //->prependFile($this->basePath() . '/javascripts/foundation3/jquery.js')
;?>
<script type="text/javascript" src="<?php echo $this->basePath() . '/javascripts/9etraining-ajax.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() . '/javascripts/main.js'; ?>"></script>

<?php echo $this->inlineScript() ?>
