<nav class="top-bar" id="top-bar">
    <ul>
      <!-- Title Area -->
      <li class="name">
        <h1 id="logo">
          <a href="<?php echo $this->url('home'); ?>" title="9E Training home page.">
            <?php echo $this->translate('9E Training'); ?>
          </a>
        </h1>
      </li>
      <li class="toggle-topbar"><a href="#"></a></li>
    </ul>

    <section>

      <!-- Left Nav Section -->
      <ul class="left">
          <li class="divider"></li>
          
          <?php if ($this->isAllowed('adminLink', 'view')): ?>          
          <li><a href="<?php echo $this->url('category'); ?>">Categories</a></li>
          <li class="divider"></li>
          <li><a href="<?php echo $this->url('question'); ?>">Questions</a></li>
          <li class="divider"></li>
          <?php endif; ?>
          
          <?php if ($this->isAllowed('userLink', 'view')): ?>
          <li class="has-dropdown">
            <a class="active" href="#">Study</a>
            <ul class="dropdown">
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('study'); ?>">Study Home Page</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('study', array(
                    'action' => 'category',
                    'id' => '2',
                    )); ?>">900 Limitations</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('study', array(
                    'action' => 'category',
                    'id' => '3',
                    )); ?>">900 Memory Items</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('study', array(
                    'action' => 'category',
                    'id' => '4',
                    )); ?>">900 Emergency Checklist</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('study', array(
                    'action' => 'category',
                    'id' => '5',
                    )); ?>">900 Aircraft General</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('study', array(
                    'action' => 'category',
                    'id' => '6',
                    )); ?>">900 Doors</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('study', array(
                    'action' => 'category',
                    'id' => '7',
                    )); ?>">900 EICAS</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('study', array(
                    'action' => 'category',
                    'id' => '8',
                    )); ?>">900 Auxiliary Power Unit</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('study', array(
                    'action' => 'category',
                    'id' => '9',
                    )); ?>">900 Electrical</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('study', array(
                    'action' => 'category',
                    'id' => '10',
                    )); ?>">900 Powerplant</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('study', array(
                    'action' => 'category',
                    'id' => '11',
                    )); ?>">900 Fuel System</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('study', array(
                    'action' => 'category',
                    'id' => '12',
                    )); ?>">900 Fire and Overheat</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('study', array(
                    'action' => 'category',
                    'id' => '13',
                    )); ?>">900 Pneumatics</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('study', array(
                    'action' => 'category',
                    'id' => '14',
                    )); ?>">900 Environmental Control System</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('study', array(
                    'action' => 'category',
                    'id' => '15',
                    )); ?>">900 Ice and Rain</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('study', array(
                    'action' => 'category',
                    'id' => '16',
                    )); ?>">900 Hydraulic System</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('study', array(
                    'action' => 'category',
                    'id' => '17',
                    )); ?>">900 Flight Controls</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('study', array(
                    'action' => 'category',
                    'id' => '18',
                    )); ?>">900 Landing Gear</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('study', array(
                    'action' => 'category',
                    'id' => '19',
                    )); ?>">900 Flight Instruments</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('study', array(
                    'action' => 'category',
                    'id' => '20',
                    )); ?>">900 Navigation</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('study', array(
                    'action' => 'category',
                    'id' => '21',
                    )); ?>">900 Auto Flight Control System</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('study', array(
                    'action' => 'category',
                    'id' => '22',
                    )); ?>">900 Communications</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('study', array(
                    'action' => 'category',
                    'id' => '23',
                    )); ?>">900 O2 and Emergency Equipment</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('study', array(
                    'action' => 'category',
                    'id' => '24',
                    )); ?>">900 Lighting</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('study', array(
                    'action' => 'category',
                    'id' => '25',
                    )); ?>">900 Flight Management System</a></li>
                <li class="divider"></li>
            </ul>
          </li>
          <li class="divider"></li>
          <?php endif; ?>
      </ul>

      <!-- Right Nav Section -->
      <ul class="right">
        <li class="divider hide-for-small hide-for-medium"></li>
        <li>
            <a href="<?php echo $this->url('zfcuser'); ?>" class="<?php echo $this->ajaxLink(); ?>">
                <?php echo ($this->zfcUserIdentity()) ? $this->translate('Your Account') : $this->translate('Login'); ?>
            </a>
        </li>
      </ul>
    </section>
</nav>
